<?php
$snhelper = Mage::helper('general');
$snhelper->checkCart();

$cart = Mage::getSingleton('checkout/cart');

$days = 0;
$productsprice = 0;
$aboprice = 0;
$used_days = array();

foreach($cart->getQuote()->getAllItems() as $item){
    $_item_day_week_ob = $item->getOptionByCode('day_week');
    if(is_object($_item_day_week_ob)){
        $_item_day_week = $_item_day_week_ob->getValue();
    }
    else{
        $_item_day_week = 'no day';
    }
    if($_item_day_week == 'no day'){
        $aboprice += $item->getProduct()->getPrice()*$item->getQty();
    }
    else{
        if(array_search($_item_day_week, $used_days) === false){
            $used_days[] = $_item_day_week;
            $days++;
        }
        $productsprice += $item->getProduct()->getPrice()*$item->getQty();
    }
}

$subtotal = $productsprice+$aboprice;

$customer = Mage::getSingleton('customer/session')->getCustomer();
$abonament_expiration = $customer->getAbonamentExpiration(true);
$abonament_freedays = $customer->getLeftFreeDays();
$abonament_period = $customer->getAbonamentPeriod();
$abonament_paydays = $abonament_expiration - $abonament_freedays;

$overpayment = $customer->getOverpay();
$subtotal -= $overpayment;

$sum_text = $this->__('Zapłać');

if($subtotal < 0 ){
    $sum_text = $this->__('Potwierdź');
    $subtotal = -$subtotal;
}
else if($subtotal == 0){
    $sum_text = $this->__('Potwierdź');
}
?>
<div class="sum-cart">
    <div class="sum-content">
        <div class="summary">
            <span>zaplanowałeś dostawę na <span id="sum-days"><?php echo $days; ?></span> dni: 
                <strong>
                    <?php echo number_format($productsprice, 2, ',', ''); ?> zł
                </strong>
            </span>

            <span>abonament dostawczy: <span id="abonament">
                    <?php if($abonament_paydays > 0 && $abonament_freedays > 0): ?>
                    <br>
                    <?php endif; ?>
                    <strong>
                        <?php if($abonament_expiration <= 0): ?>
                        brak
                        <?php else: ?>
                            <?php if($abonament_freedays > 0): ?>
                                <?php echo $abonament_freedays; ?> dni gratis
                            <?php endif; ?>
                            <?php if($abonament_paydays > 0 && $abonament_freedays > 0): ?>
                                +
                            <?php endif; ?>
                            <?php if($abonament_paydays > 0): ?>
                                <?php echo $abonament_paydays; ?> dni za
                                <?php echo number_format($aboprice, 2, ',', ''); ?> zł
                            <?php endif; ?>
                        <?php endif; ?>
                    </strong>
                </span>
            </span>
            <?php if($abonament_paydays > 0): ?><br>
            <span class="abo_period">
                (<?php echo $this->__('na okres').' '.$abonament_period; ?>)
            </span>
            <?php endif; ?>
            <?php if ($overpayment > 0): ?><br>
                <span>nadpłata: <span id="overpayment">
                        <strong>
                            <?php echo number_format($overpayment, 2, ',', ''); ?> zł
                        </strong>
                    </span>
                </span>
            <?php endif; ?>
            <div>
                <div class="all-sum">
                    <span>do zapłaty:</span>
                    <span id="price_total">
                        <span class="price"><strong>
                                <?php echo number_format($subtotal, 2, ',', ''); ?> zł</strong>
                        </span>
                    </span>
                </div>
            </div>
        </div>
    </div>