<?php
$category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$categories = $category->getCollection()
        ->addAttributeToSort('position', 'ASC')
        ->addAttributeToSelect(array('name', 'thumbnail'))
        ->addAttributeToSelect('all_children')
        ->addAttributeToFilter('is_active', 1);
$cat_count = count($categories);
if($cat_count == 0) $cat_count = 1;
$nav_width = floor(644/$cat_count);
$last_nav_width = 644-(($cat_count-1)*$nav_width);
        
?>
<!-- 
for display image on category use:

<img src="<?php //echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $category->getThumbnail() ?>" alt="<?php //echo $this->htmlEscape($category->getName()) ?>" />

-->
<script>
	jQuery(document).ready(function (){
/**
		var user_logging = "<?php echo $this->helper('customer')->isLoggedIn(); ?>";

		if( user_logging != 1 ){
			jQuery('.login-button').trigger('click');
		}
		
        jQuery(".login-button").colorbox({inline:true, width:"50%", closeButton: true});
        jQuery(".reghister-button").colorbox({inline:true, width:"50%", closeButton: true});

        jQuery(".back-link").click(function(){
        	jQuery('#cboxClose').trigger('click');
        });
**/
    });
</script>

<div class="menu-subcategories">
	<?php $current_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();  ?>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('offert_info')->toHtml(); ?>
	<ul class="subcategories">
            <?php $_c = 1; ?>
	    <?php foreach ($categories as $category): ?>
	        <li style="width:<?php echo ($_c++ == $cat_count) ? $last_nav_width : $nav_width; ?>px;">
	        	<?php if( $category->getId() != 2 ){ ?>
		        	<?php if( $category->getId() != 14 ){ ?>
		            		<a class="subcategories-button<?php if( $current_id == $category->getId() ): ?> selected<?php endif; ?>" href="<?php echo $category->getUrl() ?>" onclick="return false;" data-categoryid="<?php echo $category->getId(); ?>">
		                		<span<?php if(strlen($category->getName()) > 12): ?> style="font-size:16px;<?php endif; ?>"><?php echo $category->getName() ?></span></a>
		            <?php } ?>
	            <?php } ?>
	        </li>
	    <?php endforeach; ?>
	</ul>
</div>