<div class="std">
    <div class="page-title">
        <h1><?php echo __('Abonament'); ?></h1>
    </div>
    
    <div class="account-content widget-contact" style="width:600px;">
        <?php if(true): ?>
        <p class="gray">Twój abonament jest obecnie nieaktywny</p>
        <?php else: ?>
        <p class="gray">Aktywowałeś abonament dnia: <span>14 kwietnia 2014</span></p>
        <p class="gray">do końca abonamentu:</p>
        <h2 class="green">27 dni</h2>
        <p class="gray">(ostatni aktywny dzień - 11 maja)</p>
        <?php endif; ?>
        
    </div>
</div>
