<div class="std">
    <div class="page-title">
        <h1><?php echo __('Reklamacje'); ?></h1>
    </div>
    <div class="account-content widget-contact" style="width:600px;">
        <p class="heading">Jeśli chcesz zgłosić reklamację, skontaktuj się z nami za pomocą infolinii lub e-maila</p>
        <h3>Infolinia:<span style="color: #6aade4;"> 555-666-777</span></h3>
        <p>Czynna od poniedziałku do piątku<br> od 10 do 18</p>
        <h3>E-mail: <span style="color: #6aade4;">kontakt@sniadaniowo.pl<br><br></span></h3>
    </div>
</div>
