<div class="std">
    <div class="page-title">
        <h1><?php echo __('Stan konta'); ?></h1>
    </div>
    <div class="account-content widget-contact account-status" style="width:527px;">
        <p class="gray">Tutaj możesz zobaczyc jaka kwota nadpłaty pozostała Ci do wykorzystania z racji usunięcia juz oplaconych zamówień. Kwotę tę możesz przeznaczyć na poczet kolejnych zamówień lub poczekać na zwrot do 30. dnia bieżącego miesiąca.</p>
        <p class="gray">Jeśli chcesz żeby kwota ta została zwrócona wpisz poniżej swój numer konta bankowego.</p>
        <p class="gray"><big>Nadpłata: 0,00 zł</big></p>
        <p class="gray">Wpisz swój numer konta, na który będziemy zwracać twoje nadpłaty:<br>
        Jeśli nie chcesz podawać numeru konta, <a href="<?php echo Mage::getBaseUrl(); ?>/kontakt" style="text-decoration: none;">skontaktuj się z nami</a></p>
        
        <div class="account-form account-form-status">
        <form method="post" id="form_acc_number" action="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>">
            <div class="row">
                <input type="text" name="account_number" id="acc_number"  value="">
            </div>
            <div class="row">
                <input type="submit" value="<?php echo $this->__('Wyślij numer konta'); ?>">
            </div>
        </form>
        </div>
        
    </div>
</div>

<script src="/js/jquery.maskedinput-master/lib/jquery-1.9.0.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/js/jquery.maskedinput-master/dist/jquery.maskedinput.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery('#form_acc_number').submit(function(){
        var pos = 0;
        var haystack = "X" + jQuery('#acc_number').val();
        pos = haystack.indexOf('_'); 
        
        if(pos == -1)
            return true;
        
        jQuery('#acc_number').addClass('validation-failed');
        
        return false;
    });
    
    jQuery(function() {
        jQuery("#acc_number").mask("99 9999 9999 9999 9999 9999 9999", { autoclear: false });
    });

</script>

<style>
.main-container-subpage .account-form .row {
    clear: both;
    float: left;
    text-align: center;
    width: 100%;
}
</style>
